-- AlterTable
ALTER TABLE `notifications` MODIFY `type` ENUM('NEW_SCHOLAR_SUBMISSION', 'EDIT_PROPOSAL', 'REPORT_SUBMITTED', 'COMMENT_ON_BLOG', 'COMMENT_ON_SCHOLAR', 'SCHOLAR_APPROVED', 'SCHOLAR_REJECTED', 'MEDIA_APPROVED', 'MEDIA_REJECTED', 'NEW_DISCIPLINE_SUBMISSION') NULL;
