-- AlterTable
ALTER TABLE `media` ADD COLUMN `author` VARCHAR(255) NULL,
    ADD COLUMN `description` TEXT NULL,
    ADD COLUMN `format` ENUM('BOOK', 'ARTICLE', 'THESIS', 'MANUSCRIPT', 'LECTURE', 'VIDEO', 'AUDIO', 'PODCAST', 'INTERVIEW', 'DOCUMENTARY', 'COURSE', 'CONFERENCE', 'WEBSITE', 'OTHER') NULL,
    ADD COLUMN `publisher` VARCHAR(255) NULL,
    ADD COLUMN `title` VARCHAR(255) NULL,
    ADD COLUMN `year` INTEGER NULL;
